infrastructure_version = "v2"
owner                  = "sameershah21"
service                = "aws infra"
function               = "s3 bucket"
github_repository_name = "kitchen-inspec-tf-assignment-li"
